# Generated by Django 2.1.7 on 2019-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField()),
                ('team_logo', models.FileField(blank=True, upload_to='media/team-pics')),
            ],
            options={
                'ordering': ['-team_name'],
            },
        ),
    ]
