# Generated by Django 2.1.7 on 2019-03-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_name']},
        ),
    ]
