# Generated by Django 2.1.7 on 2019-03-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_auto_20190320_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('birth_date', models.DateField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('dribbling', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('physical', models.IntegerField()),
                ('shooting', models.IntegerField()),
                ('defending', models.IntegerField()),
                ('pace', models.IntegerField()),
                ('position', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='team.Team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
