# Generated by Django 2.1.7 on 2019-04-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20190401_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
    ]
